#!/bin/bash

# OCP Prometheus Connectivity Troubleshooting Script
# This script helps diagnose and fix connectivity issues with OCP federate endpoints

echo "=== OCP Prometheus Connectivity Troubleshooting ==="
echo

# Check if we're connected to OCP cluster
echo "1. Checking OCP cluster connectivity..."
if command -v oc &> /dev/null; then
    if oc cluster-info &> /dev/null; then
        echo "✅ Connected to OCP cluster"
        CLUSTER_URL=$(oc cluster-info | grep "Kubernetes control plane" | awk '{print $NF}')
        echo "   Cluster URL: $CLUSTER_URL"
    else
        echo "❌ Not connected to OCP cluster"
        echo "   Please run: oc login <your-cluster-url>"
        exit 1
    fi
else
    echo "❌ oc command not found"
    echo "   Please install OpenShift CLI"
    exit 1
fi

echo

# Check service account and token
echo "2. Checking service account and token..."
if [ -f "ocp-federate.token" ]; then
    echo "✅ Token file exists"
    TOKEN_SIZE=$(wc -c < ocp-federate.token)
    echo "   Token size: $TOKEN_SIZE bytes"
    
    # Check if token is valid (basic JWT structure check)
    if [[ $(head -c 20 ocp-federate.token) =~ ^eyJ ]]; then
        echo "✅ Token appears to be a valid JWT"
    else
        echo "❌ Token doesn't appear to be a valid JWT"
    fi
else
    echo "❌ Token file not found"
    echo "   Please run: ./setup-service-account.sh"
    exit 1
fi

echo

# Check if service account exists
echo "3. Checking service account..."
if oc get sa federator -n openshift-monitoring &> /dev/null; then
    echo "✅ Service account 'federator' exists"
else
    echo "❌ Service account 'federator' not found"
    echo "   Please run: ./setup-service-account.sh"
    exit 1
fi

echo

# Get current cluster endpoints
echo "4. Getting current cluster endpoints..."
echo "   Checking openshift-monitoring routes..."

# Check for prometheus-k8s route
PROMETHEUS_ROUTE=$(oc -n openshift-monitoring get route prometheus-k8s -o jsonpath='{.spec.host}' 2>/dev/null)
if [ -n "$PROMETHEUS_ROUTE" ]; then
    echo "✅ Prometheus route found: $PROMETHEUS_ROUTE"
else
    echo "❌ Prometheus route not found"
fi

# Check for thanos-querier route
THANOS_ROUTE=$(oc -n openshift-monitoring get route thanos-querier -o jsonpath='{.spec.host}' 2>/dev/null)
if [ -n "$THANOS_ROUTE" ]; then
    echo "✅ Thanos Querier route found: $THANOS_ROUTE"
else
    echo "❌ Thanos Querier route not found"
fi

# Check for user workload monitoring routes
echo "   Checking openshift-user-workload-monitoring routes..."
UWM_ROUTE=$(oc -n openshift-user-workload-monitoring get route prometheus-user-workload -o jsonpath='{.spec.host}' 2>/dev/null)
if [ -n "$UWM_ROUTE" ]; then
    echo "✅ User Workload Monitoring route found: $UWM_ROUTE"
else
    echo "❌ User Workload Monitoring route not found"
fi

echo

# Test connectivity to available endpoints
echo "5. Testing connectivity to available endpoints..."

if [ -n "$THANOS_ROUTE" ]; then
    echo "   Testing Thanos Querier endpoint..."
    RESPONSE=$(curl -k -H "Authorization: Bearer $(cat ocp-federate.token)" -w "HTTP Status: %{http_code}\nTotal Time: %{time_total}s\n" -o /dev/null -s "https://$THANOS_ROUTE/api/v1/query?query=up" --max-time 30)
    if [ $? -eq 0 ]; then
        echo "✅ Thanos Querier is reachable"
        echo "   Response: $RESPONSE"
    else
        echo "❌ Thanos Querier is not reachable"
        echo "   Response: $RESPONSE"
    fi
fi

if [ -n "$UWM_ROUTE" ]; then
    echo "   Testing User Workload Monitoring endpoint..."
    RESPONSE=$(curl -k -H "Authorization: Bearer $(cat ocp-federate.token)" -w "HTTP Status: %{http_code}\nTotal Time: %{time_total}s\n" -o /dev/null -s "https://$UWM_ROUTE/federate?match[]={__name__=\"up\"}" --max-time 30)
    if [ $? -eq 0 ]; then
        echo "✅ User Workload Monitoring is reachable"
        echo "   Response: $RESPONSE"
    else
        echo "❌ User Workload Monitoring is not reachable"
        echo "   Response: $RESPONSE"
    fi
fi

echo

# Generate updated Prometheus configuration
echo "6. Generating updated Prometheus configuration..."
cat > prometheus-updated.yaml << EOF
# Updated Prometheus Configuration for OCP Cluster Scraping
# Generated by troubleshoot-connectivity.sh

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ocp-cluster'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Configure your AlertManager targets here
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  # Add your custom alert rules here

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
EOF

# Add Thanos Querier configuration if available
if [ -n "$THANOS_ROUTE" ]; then
    cat >> prometheus-updated.yaml << EOF
  # OCP Cluster Monitoring via Thanos Querier (Federation)
  - job_name: 'ocp-cluster-federation'
    bearer_token_file: '/etc/prometheus/secrets/ocp-federate.token'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: 
        - '$THANOS_ROUTE'
    metrics_path: '/federate'
    params:
      'match[]':
        - '{__name__=~".+"}'  # Federate all metrics
    scrape_interval: 30s
    scrape_timeout: 30s  # Increased timeout

  # OCP Cluster Monitoring via Thanos Querier (Direct Query)
  - job_name: 'ocp-cluster-direct'
    bearer_token_file: '/etc/prometheus/secrets/ocp-federate.token'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: 
        - '$THANOS_ROUTE'
    metrics_path: '/api/v1/query'
    params:
      query: ['up']  # Basic connectivity test
    scrape_interval: 60s
    scrape_timeout: 30s  # Increased timeout

EOF
fi

# Add User Workload Monitoring configuration if available
if [ -n "$UWM_ROUTE" ]; then
    cat >> prometheus-updated.yaml << EOF
  # OCP User Workload Monitoring
  - job_name: 'ocp-userworkload-federation'
    bearer_token_file: '/etc/prometheus/secrets/ocp-federate.token'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: 
        - '$UWM_ROUTE'
    metrics_path: '/federate'
    params:
      'match[]':
        - '{__name__="up"}'
        - '{__name__=~"ALERTS|ALERTS_FOR_STATE"}'
        - '{job!~"prometheus.*|thanos.*"}'
        - '{namespace!~"openshift-.*"}'
    scrape_interval: 30s
    scrape_timeout: 30s  # Increased timeout

EOF
fi

# Add Prometheus self-monitoring
cat >> prometheus-updated.yaml << EOF
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
EOF

echo "✅ Updated Prometheus configuration generated: prometheus-updated.yaml"
echo

# Provide next steps
echo "7. Next Steps:"
echo "   1. Review the generated prometheus-updated.yaml file"
echo "   2. Copy it to your Prometheus configuration directory:"
echo "      sudo cp prometheus-updated.yaml /etc/prometheus/prometheus.yaml"
echo "   3. Restart Prometheus:"
echo "      sudo systemctl restart prometheus"
echo "   4. Check Prometheus targets in the web UI"
echo

echo "=== Troubleshooting Complete ==="


